name: BPM
favicon: null
layout_spectrum: 0.6092088054865599
typography_spectrum: 0.09670863975770772
title: BUERO PHILIPP MOELLER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.07662356807850301
  lightness: 0.0015361064579337835
  saturation: 0.9037575656548142
  rhythmicContrast: 0.17955763987265527
purpose: []
